### ISSUE TITLE
The distribution file for EPPO code LASPMO was not found. Error in distri_lists[[i]] : subscript out of limit

### ISSUE THREAD

**Issue by giovabubi** [mczyzj/pestr#25]
Hello!
when I run the following R code
`pest_distri <- pestr::eppo_tabletools_distri(pests_names_tables)`
I get the following error:
```
The distribution file for EPPO code LASPMO was not found.
Error in distri_lists[[i]]: subscript out of limit.
```
And this is for all names I search. In the past, I used successfully this code. Has something changed? Is distribution data not yet available?

**Comment by mczyzj** [comment]
@giovabubi hey, thank you for using the package:) You are right, EPPO made some changes to the distribution files structure. I already covered it in development version of the package, which is not yet published on CRAN. If you install the development version of the package it should work fine:
```
# install.packages("devtools")
devtools::install_github("mczyzj/pestr", force = TRUE)
```
Please, let me know if that solved the problem.

Good luck!

**Comment by giovabubi** [comment]
Now, it works. Thank you so much!
